# Generated by Django 4.2.7 on 2023-12-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='cep',
            field=models.CharField(default=True, max_length=8, null=True),
        ),
    ]
