# Generated by Django 4.2.7 on 2023-12-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_address_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='cep',
            field=models.CharField(default=23145675, max_length=8),
            preserve_default=False,
        ),
    ]
