# Generated by Django 4.2.7 on 2023-12-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_profile_address_profile_cep_profile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='house_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profileImages/11_12_2023'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_reseller',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
