# Generated by Django 4.2.7 on 2024-02-02 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0016_alter_profile_image_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profileImages/02_02_2024'),
        ),
        migrations.CreateModel(
            name='lojista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=16)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lojistasImages/02_02_2024')),
                ('cnpj', models.CharField(max_length=14)),
                ('cep', models.CharField(max_length=8)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('complement', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proprietario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
