# Generated by Django 4.2.7 on 2024-02-02 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0017_remove_profile_user_alter_profile_image_lojista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lojista',
            name='proprietario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
