# Generated by Django 4.2.7 on 2024-02-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_lojista_proprietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lojista',
            name='image',
            field=models.ImageField(upload_to='lojistasImages/04_02_2024'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profileImages/04_02_2024'),
        ),
    ]
