# Generated by Django 4.2.7 on 2024-02-19 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_remove_lojista_categories_lojista_tags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lojista',
            old_name='tags',
            new_name='categories',
        ),
    ]
