# Generated by Django 4.2.6 on 2023-11-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_nome_product_name_rename_user_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='mkmkmk'),
            preserve_default=False,
        ),
    ]
