# Generated by Django 4.2.6 on 2023-11-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_bag_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='product.product'),
        ),
    ]
