# Generated by Django 4.2.6 on 2023-11-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_bag_products_bag_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='products',
        ),
        migrations.AddField(
            model_name='bag',
            name='products',
            field=models.ManyToManyField(blank=True, to='product.product'),
        ),
    ]
