# Generated by Django 4.2.7 on 2023-12-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_product_image_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageTeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='media_root/')),
            ],
        ),
    ]
